[package]
authors = ["Jorge D. Ortiz-Fuentes <jdortiz@gmail.com>"]
name = "lazycoder"
description = "Simple snippet provider for espanso."
version = "0.7.10"
edition = "2024"

[dependencies]
clap = { version = "~4.6", features = ["derive"] }
directories = "~6.0"
env_logger = "~0.11"
eyre = "~0.6"
log = "~0.4"
serde = "^1.0"
serde_derive = "^1.0"
toml = "~1.1"

[dev-dependencies]
mockall = "~0.14"
mockall_double = "~0.3"
tempfile = "~3.27"

[lints.clippy]
pedantic = "warn"
